### ISSUE TITLE
Logical ops for trait evaluation and property checking

### ISSUE THREAD

**Issue by Manu343726** [pfultz2/Tick#6]
`is_true` and `is_false` work nice, but I find myself doing n-ary `std::integral_constant<bool, A::value || B::value || ...>` many times, so I will be glad if there's some support for or operations out of the box. The usual n-ary `or_` metafunction should do the trick.

By default `valid` is an `and` since it's instanced successfully only if all its parameters are valid. In many cases, a concept requirement is not a set of mandatory properties in a way that all of them should be accomplished by the type, but a set of possible properties.

**Comment by pfultz2** [comment]
> is_true and is_false work nice, but I find myself doing n-ary std::integral_constant<bool, A::value || B::value || ...>

There is `is_true_c` and `is_false_c` that take a boolean directly, so you don't have to wrap it in an integral constant. So you should just be able to write `is_true_c<(A() || B() || ...)>` directly.

> The usual n-ary or_ metafunction should do the trick.

I would prefer not to add that to this library, since this is a traits library and not a metaprogramming library. I believe Eric Niebler's [meta](https://github.com/ericniebler/meta) library has an [`or_`](https://ericniebler.github.io/meta/group__logical.html#ga9ca5af65887ca2392d48c549b5ce0951) metafunction.

> In many cases, a concept requirement is not a set of mandatory properties in a way that all of them should be accomplished by the type, but a set of possible properties.

Usually when you need an `or` of the type requirements is when overloading is involved. However, you can just check if the expression is valid instead. For example, a generic `print` that works for any streamable type as well as for tuples and ranges could be written like this using the Fit library:

```cpp
FIT_STATIC_FUNCTION(print) = fit::conditional(
    [](const auto& x) -> decltype(std::cout << x, void())
    {
        std::cout << x << std::endl;
    },
    [](const auto& range) -> decltype(std::cout << *adl::adl_begin(range), void())
    {
        for(const auto& x:range) std::cout << x << std::endl;
    },
    [](const auto& tuple) -> decltype(for_each_tuple(tuple, fit::identity), void())
    {
        return for_each_tuple(tuple, [](const auto& x)
        {
            std::cout << x << std::endl;
        });
    }
);
```

Rather than check with `or` that it meets the requirements of each overload, I can instead just check if `print` is a valid expression:

```cpp
TICK_TRAIT(is_printable)
{
    template<class T>
    auto require(const T& x) -> decltype(print(x));
};
```

**Comment by sbergen** [comment]
Just as a note for anyone else browsing this: C++17 has std::disjunction for logical or on type traits. You can easily replicate it if your compiler doesn't have C++17 support, see: http://en.cppreference.com/w/cpp/types/disjunction

Also, would be nice if is_true_c and is_false_c would be mentioned in the documentation: I had a really hard time finding them...
